name: workflow_01

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: print a welcome message
        run: echo "Hellooooo"

      - name: test urself
        run: echo "idk what to write"
